audreyt/ethercalc

db.js
src/db.ls

Very simple PR. I'm not a user of LiveScript but I tried to remain close to the style I found here. Thanks.

Allow selecting database number with REDIS_DB environment variable

---

socialcalctableeditor.js

I think this could have a better user experience.

New feature: Paste single cell of clipboard to select range.

---

socialcalcspreadsheetcontrol.js
static/jszip.js
static/xlsx.js

I've changed some of the tooltips to make it clearer to first time users what each of the buttons do.
In reality, I would like to change the icons to something like the ones in font-awesome (the current ones are quite ugly)
I also had a problem uploading an xls sheet to Ethercalc - it was a problem with xlsx.js - so I've updated that (and jszip)

Small UI and dependency changes

---

start.html

I thought it would be nice to be able to give spreadsheets a different name after uploading (to make the URL pretty)
One thing this check does not do is check to see a sheet with the same name already exists. Having said that, the current `newId()` method doesn't do this either (I guess it's not very likely for the same ID to be created twice, but it's possible)
What I'd like to do is add a check to see if either the auto-generated ID or the entered name already exists. If it does then it either prompts for a new name, or generates a new ID.
My LiveScript skills are very poor though, so any pointers would be helpful :-)

Allow renaming of uploaded spreadsheets

---

apache/apache-proxy.conf

Also document using Apache to serve the static files
It's just a simple config file, but I thought it would be useful to document how to get basic auth and proxy pass settings working.
The websockets proxy pass is kind of important as well. I was also finding node on my (slow) server was having trouble serving all the static files - it's something Apache should really be doing :-)

Add an apache proxy config file

---

apache/apache-proxy.conf

@audreyt  - You were too merging my other PR ;-)
I noticed the images and l10n folders should also be aliased

Also alias images and l10n folders aliases to conf

---

socialcalctableeditor.js

This adds the ability to select an entire row or column by clicking
on the row or column header.

add in selection by row and column

---

Makefile

This generates source maps so that a debugger can be used to debug
socialcalc.

generate source maps

---

index.html

This adds the spreadsheet name to the title, which allows the user
to easily switch between different tabbed spreadsheets.

add spreadsheet name to title

---

socialcalctableeditor.js

Refactor event code

---

socialcalctableeditor.js

This patch adds mouse drag to row/col select.  Fixes issue #263

add drag to row/col select

---

formula1.js

Fixes #228
This adds the ability to use * and ? in the COUNTIF (and similar) functions. I used the exact criteria as defined in #228

Add wildcard/single char matching for COUNTIF

---

formula1.js

A few more things I wanted in my last PR. This makes sure regex search works for multiple ?? or ** etc. in the search string.

Fix up wildcard searching with multiple ? and *

---

API.md

 add new API to list

---

misc/archive.ls

The automatic archiving is triggered only if PUT_IN_HISTORY is set.

Calc automatic archiving in static/history (archive.ls)

---

socialcalc-3.js
socialcalcspreadsheetcontrol.js
socialcalctableeditor.js

At the moment, only a few of the cells would be selected. This isn't very useful for example when you want to change the background colour of an entire row. What I have done now is the next step, but still not ideal. (Ideally, the whole row/col going on to 'infinity' would be selected)
@joequant - it is your code I've changed

When selecting rows/cols, select all the way to the end of the row/col.

---

socialcalc-3.js

Taking care of french locale conventions:
MM/DD/YYYY  > DD/MM/YYYY  for french language ('fr')

Date formatting for french users

---

misc/archive.ls

+ I moved some PUT_IN_HISTORY stuff outside the foreach snapshot-* record loop as it needs to be run only one time

Archive.ls: create 'raw' dir if needed

---

LICENSE.txt
bin/run.sh
bin/runSafe.sh

Taken from Etherpad
This allows you to:
* restart automatically when Ethercalc crashes (`safeRun.sh`)
* add a log file for Ethercalc (`safeRun.sh /path/to/my/logfile.log`)
* send logs via mail when restarts occur (not tested, but it says this in the script)
**Edit:** Fixes https://github.com/audreyt/ethercalc/issues/348 now, too.

Add startup scripts

---

Dockerfile
README.mkdn
docker-compose.yml
misc/ethercalc.sh
misc/linux-install-docker-and-compose.sh

* included simple bash script to install docker and compose on linux
* added compose container orchestration config
* updated readme instructions

easier ethercalc container deploy with docker-compose

---

start.html
static/start.css
static/start.sass

preparing for a modification
removed large blocks of inline style definitions and added them to css file instead
unminified the css file for the time being

start.html formatting

---

index.html
panels.html
start.html

So that the paths also work when Ethercalc is installed in a subdirectory.

Change Favicon paths for subdirectory

---

bin/run.sh

https://github.com/audreyt/ethercalc/issues/404

Fixes issue #404

---

package.json

Update zappajs to 5.x

---

src/player-graph.ls

Implement col/row resize-bar of head. [Screen Shot Preview](http://imgur.com/a/0IAaZ)

Improve the resize-bar UX of head on mouse hover it.

---

index.html

Change "en_US" to "en-US" etc as per http://stackoverflow.com/questions/5580876/navigator-language-list-of-all-languages
Fixes minor issue with: https://github.com/audreyt/ethercalc/commit/575eea36b15c27fbf6380e2244ec1a05b0035dc5

Fix - Do not emit en_US 404 errors. Closes #386.

---

Makefile

This fixes the Makefile so that it does not create bad files if
sass or uglify are missing.

fix Makefile to deal with missing sass and uglify

---

db.js
src/db.ls

This PR addresses [an issue that was identified during the review](https://github.com/audreyt/ethercalc/pull/597#discussion_r174136544) from PR #597.

Filter extra blank line when restoring from audit file

---

src/main.ls

This works for me when I use` --basepath ethercalc`.
I have to admit I did not test it *without* `--basepath ...`.

actually use BASEPATH - fixes #452

---

main.js
src/main.ls

Makes the multi sheet mode work again!

Fix broken multi sheet feature.

---

README.mkdn

Hi there,
I adjusted the README with more explicit steps for non-root installations.
Cheers,
tpltnt

readme adjustment
